name: Docker Image CI

on: 
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # Docker 이미지 빌드
    - name: Build Docker image
      run: |
        docker buildx build --platform=linux/amd64,linux/arm64 -t sebrinu/back-end-ws .

    # Docker 로그인
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}  # 생성한 API 토큰 사용

    # Docker 이미지 푸시
    - name: Push Docker image
      run: |
        docker push sebrinu/back-end-ws

    # 5. Jenkins 빌드 트리거
    - name: Trigger Jenkins build
      run: |
        curl -X POST http://http://34.47.90.90:8080/job/jenkinsPipelineForBackEnd/build --user ${{ secrets.JENKINS_USERNAME }}:${{ secrets.JENKINS_API_TOKEN }}
